# Generated by Django 3.1 on 2021-04-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleh',
            name='image',
            field=models.ImageField(blank=True, upload_to='Post_image'),
        ),
    ]
