# Generated by Django 3.1 on 2021-04-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleh', '0002_saleh_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleh',
            name='image',
            field=models.ImageField(blank=True, upload_to='ebrahim'),
        ),
    ]
