# Generated by Django 3.1 on 2021-04-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleh', '0006_auto_20210409_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='myname',
            name='image',
            field=models.ImageField(blank=True, upload_to='goodebrahim'),
        ),
    ]
