# Generated by Django 3.1 on 2021-04-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleh', '0007_myname_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('your_stoory', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='goodebrahim')),
            ],
        ),
    ]
