# Generated by Django 3.1 on 2021-04-10 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saleh', '0008_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='description',
            new_name='bookdescription',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='booktitle',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='your_stoory',
            new_name='bookyour_stoory',
        ),
    ]
