# Generated by Django 3.1 on 2021-04-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleh', '0010_remove_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
