# Generated by Django 3.1 on 2021-04-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleh', '0011_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookyour_stoory',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
