# Generated by Django 3.1 on 2021-04-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleh', '0012_auto_20210410_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookdescription',
        ),
        migrations.AddField(
            model_name='book',
            name='treedescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
