# Generated by Django 3.1 on 2021-04-10 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saleh', '0013_auto_20210410_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myname',
            name='image',
        ),
        migrations.RemoveField(
            model_name='myname',
            name='your_stoory',
        ),
    ]
