# Generated by Django 3.1 on 2021-04-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleh', '0014_auto_20210410_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='book',
        ),
    ]
