# Generated by Django 3.1 on 2021-04-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleh', '0017_quote_quotecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('your_stoory', models.TextField(blank=True)),
                ('salehw', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.DeleteModel(
            name='QuoteCategory',
        ),
    ]
